### ISSUE TITLE
Uncaught Error: watch $ATOM_HOME/package-switch.bundles ENOSPC

### ISSUE THREAD

**Issue by jhessin** [aminya/package-switch#10]
[Enter steps to reproduce:]

1. Load atom with a project (I loaded two projects from the command line)
2. Run Package Switch: Start

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Ubuntu 17.10
**Thrown From**: [package-switch](https://github.com/deprint/package-switch) package 0.5.0

### Stack Trace

Uncaught Error: watch /home/jhessin/.atom/package-switch.bundles ENOSPC

```
At fs.js:1318

Error: watch /home/jhessin/.atom/package-switch.bundles ENOSPC
    at exports._errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1316:19)
    at Object.fs.watch (fs.js:1341:11)
    at /packages/package-switch/lib/bundles.coffee:25:23)
    at Object.createBundlesInstance (/packages/package-switch/lib/main.coffee:36:17)
    at Object.create (/packages/package-switch/lib/main.coffee:149:6)
    at /packages/package-switch/lib/main.coffee:43:89)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:388:36)
    at Object.didConfirmSelection (/usr/share/atom/resources/app/node_modules/command-palette/lib/command-palette-view.js:143:35)
    at SelectListView.confirmSelection (/usr/share/atom/resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:327:26)
    at HTMLDivElement.core:confirm (/usr/share/atom/resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:84:20)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
     -3:44.6.0 command-palette:toggle (div.panels-item)
     -3:42.2.0 core:confirm (input.hidden-input)
     -3:42.2.0 timecop:view (div.panels-item)
     -0:19 command-palette:toggle (div.timecop.pane-item.native-key-bindings)
     -0:16.8.0 core:confirm (input.hidden-input)
     -0:16.8.0 package-switch:create (div.timecop.pane-item.native-key-bindings)
```

### Non-Core Packages

```
atom-ide-ui 0.8.1 
auto-softwrap 1.0.1 
autocomplete-glsl 0.2.3 
autocomplete-love 0.4.0 
autocomplete-lua 0.9.0 
autocomplete-modules 1.10.0 
black-ui 0.3.5 
build-tools 4.5.12 
busy-signal 1.4.3 
chary-tree-view 0.2.13 
city-lights-icons 1.1.1 
coffee-navigator 0.0.18 
coffee-paste 0.8.0 
editorconfig 2.2.2 
hyperclick 0.1.5 
hyperclick-love 0.6.0 
hyperlink-hyperclick 1.3.4 
ide-flowtype 0.18.0 
indentation-indicator 1.1.0 
intentions 1.1.5 
ir-black-k-syntax 0.2.3 
js-hyperclick 1.13.0 
language-gitignore 0.3.0 
language-glsl 2.0.4 
language-lua 0.9.11 
language-markdown 0.25.1 
linter 2.2.0 
linter-coffeelint 1.3.1 
linter-eslint 8.4.1 
linter-flow-plus 3.1.0 
linter-luacheck 2.0.1 
linter-ui-default 1.6.10 
love-ide 0.17.0 
package-switch 0.5.0 
path-hyperclick 0.3.0 
platformio-ide-terminal 2.8.0 
prettier-atom 0.49.2 
space-tab 0.4.2 
standardjs-snippets 2.6.2 
sync-settings 0.8.3 
zentabs 0.8.9 
```

**Comment by fstiewitz** [comment]
Your OS is throwing an `ENOSPC` which normally means your HDD is full.

In this context it probably means that you have exceeded the number of inotify watches per user. [Try increasing the limit](https://flight-manual.atom.io/hacking-atom/sections/hacking-on-atom-core/#typeerror-unable-to-watch-path).

The package can't do anything about it but a more descriptive error message should make it more clear.
